### ISSUE TITLE
Read More link disappears if GA setting not selected

### ISSUE THREAD

**Issue by robincornett** [RRWD/genesis-accessible#14]
If the "Add the post title to the read more links" setting is not checked in Genesis Accessible, no "read more" links display on archives at all. The function in the wp-modification.php file should be adjusted to prevent this:

```php
function genwpacc_read_more_link( $link ) {
	if ( genesis_get_option( 'genwpacc_read_more', 'genwpacc-settings' )  == 0 ) return $link;
	// http://wpfab.com/edit-the-read-more-link-on-blog-or-content-archive-pages/
	return '...<br /> <a href="'. get_permalink() .'" class="more-link">' . __( 'Read more', 'genesis' ) . '<span class="more-link-title"> ' . __( 'about', GENWPACC_DOMAIN ) . " " . get_the_title() . "</span></a>";
}
```
(the filter should return the original link, at the very least)

**Comment by RRWD** [comment]
Thanks, Changed it

**Comment by RRWD** [comment]
Fixed in commit https://github.com/RRWD/genesis-accessible/commit/6639cf71a4ac87606fcc2374918c0e7540c75c93
