### ISSUE TITLE
Change genesis hook for skip links

### ISSUE THREAD

**Issue by robincornett** [RRWD/genesis-accessible#15]
A lot of my child themes, and others, are moving the primary navigation so that it's above the header, which means it's also above the skip links, which are currently hooked into `genesis_header`. Please consider an earlier hook, probably `genesis_before`, so that the skip links are always first in line.

**Comment by RRWD** [comment]
In Genesis 2.2 it's loaded at:
add_action ( 'genesis_before_header', 'genesis_skip_links', 5 );
Is this soon enough? I  will make it the same for the plugin then
