### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by neilgee** [RRWD/genesis-accessible#20]
I am finding that search functionality is inoperable when plugin is active.

**Comment by GaryJones** [comment]
You're going to need to explain more please.

Is the search field not clickable / tabbable into? Does the search button not work? Does the UI work but no search results come up? Got a URL to demonstrate?

**Comment by neilgee** [comment]
http://themes.wpbeaches.com/samplemenu/
UI not working

**Comment by GaryJones** [comment]
Looks like the `<form>` element is missing.

We'll take a look. Thanks for reporting!

**Comment by RRWD** [comment]
Thanks Neil,
I added the missing
```php
$form  = sprintf( '<form %s>', genesis_attr( 'search-form' ) );
```
@neilgee can you check if this works

**Comment by neilgee** [comment]
Yes working now
