### ISSUE TITLE
Add label context for Genesis widget visibility

### ISSUE THREAD

**Issue by cdils** [RRWD/genesis-accessible#21]
For people using > Genesis 2.2, they'll see an option to "Remove less accessible Genesis widgets"

Once someone updates to 2.2+, the wording on that option becomes "Remove Genesis widgets."

Suggest adding some verbiage to label to clarify the benefit (or why someone would want to) "Remove Genesis widgets" - maybe something along the lines of:

Remove Genesis widgets (not necessary for accessibility, but does de-clutter the list of available widgets in the case these widgets are not needed)

**Comment by RRWD** [comment]
This makes me think, better remove the option. Because the plugin is strictly focussing on accessibility, this option is not necessary anymore, since the widgets are accessible now.

@cdils: Agree on removing this option and leave the widgets alone for G2.2?

**Comment by GaryJones** [comment]
Pretty sure this issue is redundant now :-)
