### ISSUE TITLE
After update: skiplinks section takes up space and pushes header down

### ISSUE THREAD

**Issue by patrickodacre** [RRWD/genesis-accessible#22]
Just updated.

I added this to style.css as a fix: 

.site-container + section {
	clip: rect(0, 0, 0, 0);
}

**Comment by RRWD** [comment]
Hey Patrick,
Do you have a link to the theme where this happens?
And what is the browser you are seeing this?

**Comment by RRWD** [comment]
ha! Good you've got it working again, thanks for letting me know :-)
