### ISSUE TITLE
Genesis 404 Not Working?

### ISSUE THREAD

**Issue by savvyjackie** [RRWD/genesis-accessible#23]
I may have stumbled on a conflict with the Genesis Accessible plugin

The Genesis 404 page default search does not work when using this plugin. I have tested it on a sample site as well as my own.

www.sample.com/badurl

When you arrive at a 404 page - if you enter search text from the prompt, the resulting search is using the 404 url to add the search query to.

Bad Url that takes you to the 404 page:
http://www.sample.com/badurl

From there, enter ‘searchtext' in search box:
The resulting search fails because the url is not correct
http://www.sample.com/badurl?s=searchtext
Should be:
http://www.sample.com/?s=searchtext

Whether or not you check use Accessible 404 page has no effect.

**Comment by RRWD** [comment]
@savvyjackie I think this wil solve your issue, can you test this?

**Comment by savvyjackie** [comment]
I can confirm that it is working properly now on G2.1.2 - thank you. :)

**Comment by RRWD** [comment]
@savvyjackie thanks for testing :-)
