### ISSUE TITLE
Widget Area Titles

### ISSUE THREAD

**Issue by GaryJones** [RRWD/genesis-accessible#3]
Suggestion is to add a `<h2 class="screen-reader-text">{$widget-area-name}</h2>` to the top of widget areas (and make widget titles change to `h3`, instead of `h2`, from the Genesis default of `h4`).

This changes the outline when the widget area is the HTML5 outline from (genesis-accessible.org home page):

![screenshot 2014-07-26 01 49 16](https://cloud.githubusercontent.com/assets/88371/3709722/2d728676-145f-11e4-93ed-ab69028b7fc2.png)

to:

![screenshot 2014-07-26 01 48 54](https://cloud.githubusercontent.com/assets/88371/3709723/34f06bb6-145f-11e4-831b-9ebcc2293b02.png)

Notice the _Untiled ASIDE_ is now `Primary Sidebar`. In XHTML when there's a div, the heading can still provide an jump target for supported AT UAs.

**Comment by RRWD** [comment]
I will leave this an issue, as a reminder that this needs more work and thought. In GA version 2.0 the headings of the widget area's are now named after the sidebar/footer/heading name

**Comment by GaryJones** [comment]
Pretty sure this is now all covered by Genesis 2.x core, when the accessibility support is enabled.
