### ISSUE TITLE
Search form improvements

### ISSUE THREAD

**Issue by GaryJones** [RRWD/genesis-accessible#6]
The label of the search form is linked to the placeholder / value, so if you search for "foobar", the <label> will then show "foobar" instead of "Search" or similar.

I'd prefer to see the `<button>` element used for the search button (clue is in the name), rather than another input. It makes it a little cleaner to target with CSS. It also allows a wider range of button content.

Might the button benefit from an `aria-label`? That way, it's a little more accessible, whatever the button content ends up as.

The `for` attribute value should be escaped.

**Comment by RRWD** [comment]
@GaryJ I want to avoid using aria-label as much as possible and stick to plain HTML is I can. To my experience this works best for all screen readers, I want to use ARIA only if the construction is not logical for screen reader users, and this is just basic HTML.
Input submit is valid and the same as in Genesis 2.2
