### ISSUE TITLE
Dropdown script

### ISSUE THREAD

**Issue by GaryJones** [RRWD/genesis-accessible#8]
While the genwpacc-dropdown.js code looks considerably better now it's in a module, it still has some issues:

* The mouseleave `delay()` bit doesn't work at all, since that is only for animations. Without that bit working, it's pointless adding the class for mouseenter in the first place.
* The settings are mixed in with the functionality. Changing the hover class means editing in three places, and that opens up the chance of human error.
* The code has no unit tests.
* The code can't be pulled into a theme for concatenating and minifying for performance benefits.

I've created a new jQuery plugin: https://github.com/GaryJones/accessible-menu . It:

* Fixes the [timeout](https://github.com/GaryJones/accessible-menu/blob/1.0.0/src/jquery.accessible-menu.js#L54) and attempts to [clear](https://github.com/GaryJones/accessible-menu/blob/1.0.0/src/jquery.accessible-menu.js#L36) the timeouts when another menu item is hovered over.
* Has [public options](https://github.com/GaryJones/accessible-menu/tree/1.0.0#documentation) that can be set [globally](https://github.com/GaryJones/accessible-menu/blob/1.0.0/src/jquery.accessible-menu.js#L82) or at [run-time](https://github.com/GaryJones/accessible-menu/tree/1.0.0#examples)
* Comes in [minified](https://github.com/GaryJones/accessible-menu/blob/1.0.0/dist/jquery.accessible-menu.min.js) or [unminified](https://github.com/GaryJones/accessible-menu/blob/1.0.0/dist/jquery.accessible-menu.js) versions.
* Has [Bower support](https://github.com/GaryJones/accessible-menu/blob/1.0.0/bower.json) so it can be pulled in via Bower into a theme or plugin.
* Has [unit tests](https://github.com/GaryJones/accessible-menu/blob/1.0.0/test/accessible-menu_test.js).

If you want to update your script with the code from my plugin, go ahead.

In the grand scheme of things though, I'd like to see Genesis Accessible dropping the current script, and just enabling and configuring the Superfish script that Genesis already includes. That already enables keyboard support, delay mouseleave, but also touch events, support for hoverIntent and so on and will be far better tested in real-world scenarios than either your current script or my plugin.

**Comment by RRWD** [comment]
Closing this, SuperFish is a no go for G 2.2. And this file is only used for < Genesis 2.2. Above, it uses the one from Genesis core, that is exactly the same.
